@startuml Token_Passing

Title Example of a typical loop

Entity Arduino1
Entity Arduino2
Entity OLED


Arduino1 -> Arduino2 : Wire.Write(DATA_INDICATOR)
Arduino2 -> Arduino1 : NumberOfBytes

Arduino1 -> Arduino2 : Wire.Write(sensorData)
Arduino2 -> Arduino1 : NumberOfBytes

Arduino1 -> OLED : Print(CounterData)
OLED -> Arduino1

Arduino1 -> Arduino2 : Wire.Write(TOKEN_INDICATOR)
Arduino2 -> Arduino1 : NumberOfBytes

Arduino1 -> Arduino2 : Wire.Write(TOKEN)
Arduino2 -> Arduino1 : NumberOfBytes
@enduml

@startuml MessageProtocol

Title MessageProtocol

scale 1 as 30 pixels

concise "Message" as MSG

@0
MSG is Indicator

@8
MSG is Data

@16
MSG is {hidden}

@enduml

