@startuml BreadBake
Title BreadBake State Diagram

state ProgramSelection
    ProgramSelection: exit: ChangeProgram()

[*] -down-> Standby

Standby -> ProgramSelection : [Event_MenuButton]
ProgramSelection -> Standby
ProgramSelection -> Waiting : [Event_StartButton]
Waiting -> Processing : [TimeElapsed]

note top of Waiting
    If the function isn't required, we pass time = -1
end note

state Processing {
    state Baking
        Baking: Entry: StartBake(Minutes)
    state Resting
        Resting: Entry: StartRest(Minutes)
    state Rising
        Rising: Entry: StartRise(Minutes)
    state Done
        Done: Entry: Wait(5 Minutes)

    state Kneading {
    Kneading: Entry : 
    Kneading: YeastTray.Drop(time)
    Kneading: ExtraTray.Drop(time)

    state MotorLeft
        MotorLeft: Entry: TurnLeft()
        MotorLeft: Exit: Stop()
    state MotorRight
        MotorRight: Entry: TurnRight()
        MotorRight: Exit: Stop()

    [*] --> MotorLeft

    MotorLeft -Left-> MotorRight : [TimeElapsed == 1 Minute]
    MotorRight -Right-> MotorLeft : [Time Elapsed == 1 Minute]
    MotorLeft --Down-> [*]
    }

    [*] -down-> Resting
    Resting --right-> Kneading 
    Kneading -> Rising 
    Rising -> Baking
    Baking -right-> Done
    Done -> [*] : [TaskNr != done || Event_MenuButton]

    Resting -down-> Cancel : [Event_MenuButton]
    Kneading -down-> Cancel : [Event_MenuButton]
    Rising -down-> Cancel : [Event_MenuButton]
    Baking -down-> Cancel : [Event_MenuButton]

    Cancel->[*]
}

Processing --> Standby : [Event_OvenDone]
@enduml